version: "3.3"
services:
  splunk-otel-collector:
    deploy:
      placement: 
        constraints: 
          - node.role == worker
      replicas: 2
    environment:
      - SPLUNK_ACCESS_TOKEN=A16LYThV-7mTwGkU6O5HZA
      - SPLUNK_REALM=us1
    ports:
      - 13133:13133
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 6060:6060
      - 7276:7276
      - 8888:8888
      - 9080:9080
      - 9411:9411
      - 9943:9943
    image: quay.io/signalfx/splunk-otel-collector:latest
networks: {}